/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class learnJNA_JNITest */

#ifndef _Included_learnJNA_JNITest
#define _Included_learnJNA_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     learnJNA_JNITest
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_learnJNA_JNITest_set
  (JNIEnv *, jclass, jint);

/*
 * Class:     learnJNA_JNITest
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_learnJNA_JNITest_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
